### ISSUE TITLE
Le PPA de Compton ne supporte pas Xubuntu 15.10

### ISSUE THREAD

**Issue by pstefanski** [Grafikart/dotfiles#1]
Erreur 404 lors de l'ajout du PPA de Compton
(https://launchpad.net/~richardgv/+archive/ubuntu/compton)

**Comment by leokun** [comment]
Hello,
Le dépot PPA n'est plus nécessaire (#2) il suffit de pull ou de  commenter/supprimer la ligne 28 du script `install/xfce`

ps : je n'ai pas corrigé dans le pull request mais la ligne 29 aussi, on a déjà assez d' `apt-get update` en amont :tongue: 
:smiley_cat:
